---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(plotly)
library(janitor)
library(tidycensus)
library(stringdist)
```


```{r}
louisiana_prison_sentences <- read_csv("lousiana_life_without_parole_sept_2021.csv") |> clean_names()
```

```{r}
ggplot(louisiana_prison_sentences, aes(x=factor(bucket_age))) +
geom_bar() +
  geom_text(aes(label = after_stat(count)), stat = "count", vjust = -.2, colour = "black") +
xlab("Bucket Age") +
ylab("Number of Incarcerated People") +
theme_linedraw()
```

```{r}
ggplot(louisiana_prison_sentences, aes(x=factor(offenses))) +
geom_bar() +
xlab("Type of Offense") +
ylab("Number of Incarcerated People") +
theme_linedraw()
```

```{r}
fig <- plot_ly(louisiana_prison_sentences, x = ~offenses, y = ~bucket_age, type = 'scatter', mode = 'markers')

fig
```

```{r}
offenses <- louisiana_prison_sentences |> group_by(offenses) |>
  summarise(total = n())

write_csv(offenses, "~/data_journalism/taylor-nichols-JOUR652/final_data_project/offenses.csv")
```

```{r}
offenses_age <- louisiana_prison_sentences |> group_by(bucket_age, offenses) |>
  summarise(total = n()) |>
  arrange(desc(total))

write_csv(offenses_age, "~/data_journalism/taylor-nichols-JOUR652/final_data_project/offenses_age.csv")
```

```{r}
age <- louisiana_prison_sentences |> group_by(bucket_age) |>
  summarise(total = n()) |>
  arrange(desc(total))

write_csv(age, "~/data_journalism/taylor-nichols-JOUR652/final_data_project/bucket_age.csv")
```

```{r}
offenses_top_15 <- offenses |> top_n(15) |>
  arrange(desc(total))

write_csv(offenses_top_15, "~/data_journalism/taylor-nichols-JOUR652/final_data_project/offenses_top_15.csv")
```
```{r}
#lets load census data
acs_variables <- load_variables(2021, "acs5", cache = TRUE)
```

```{r}
#making a data frame of racial and gender makeup of sentences
la_prison_sentences_race <- louisiana_prison_sentences |>
  group_by(race, gender) |>
  summarise (total_offenses = n())

louisiana_prison_sentences_parishes <- louisiana_prison_sentences |> 
  group_by(parish_of_conviction, race) |>
  summarise(total_convictions = n())

#pulling racial demographic data for louisiana
la_racial_demographics <- get_acs(geography = "county",
              variables = c(total_race = "B02001_001", white = "B02001_002", black = "B02001_003"),
              state = "LA",
              year = 2021)
```

```{r}
#now lets fix our demographics dataframe
la_racial_demographics_clean <- la_racial_demographics |> clean_names() |> 
   pivot_wider(names_from = variable, values_from = estimate)

```

```{r}
#more fixing and calculating percentages
la_racial_demographics_clean_2 <- la_racial_demographics_clean |> group_by(geoid) |>
  fill(total_race, white, black) |>
  filter(!is.na(total_race) & !is.na(white) & !is.na(black)) |>
  select(-moe) |> 
  mutate(pct_white = white/total_race*100, pct_black = black/total_race*100)
```

```{r}
#now lets look at the parish data before we join
louisiana_prison_sentences_parishes <- louisiana_prison_sentences_parishes |> 
  group_by(parish_of_conviction) |>
  mutate(total_parish = sum(total_convictions, na.rm = TRUE)) |> 
  ungroup()

louisiana_prison_sentences_parishes <- louisiana_prison_sentences_parishes |> 
  mutate(pct_of_total = total_convictions/total_parish*100)
```

```{r}
#ok let's try and join
# Function to find the best match

la_parishes_demographics <- louisiana_prison_sentences_parishes %>%
  mutate(matched_parish = sapply(parish_of_conviction, function(x) la_racial_demographics_clean_2$name[str_detect(tolower(la_racial_demographics_clean_2$name), tolower(x))][1])) %>%
  left_join(la_racial_demographics_clean_2, by = c("matched_parish" = "name"))

# Clean up and remove intermediate columns
la_parishes_demographics <- la_parishes_demographics %>%
  select(-matched_parish)

```
```{r}
write.csv(la_parishes_demographics, "~/data_journalism/taylor-nichols-JOUR652/final_data_project/parishes_demographics.csv")
```

```{r}
top_offenses_age <- louisiana_prison_sentences |>
  group_by(bucket_age, offenses) |>
  summarize(total_offenses = n())

write_csv(top_offenses_age, "~/data_journalism/taylor-nichols-JOUR652/final_data_project/top_offenses_age.csv")

```

```{r}
louisiana_prison_sentences |>
  group_by(offenses, bucket_age) |>
  summarise(count = n()) |>
  arrange(desc(bucket_age))5 |>
  filter(offenses == "ARMED ROBBERY")
```
```{r}
parish_conviction_count <- louisiana_prison_sentences |> group_by(parish_of_conviction) |>
  summarise(total_convictions = n())

write.csv(parish_conviction_count_total_pop, "~/data_journalism/taylor-nichols-JOUR652/final_data_project/parishes_convictions.csv")
```

```{r}
sentences <- louisiana_prison_sentences |> 
  group_by(offenses) |> 
  summarise(total_sentences = n()) |>
  arrange(desc(total_sentences)) |>
    slice(1:10) 

write_csv(sentences, "top10_sentences.csv")

```

